### ISSUE TITLE
bombing out on assert in ids.c

### ISSUE THREAD

**Issue by icepic** [kristapsdz/openrsync#10]
$ uname -a
OpenBSD xyz.inet6.se 6.4 GENERIC.MP#699 amd64
$ ./openrsync -av rsync://ftp.eu.openbsd.org/OpenBSD/6.4/octeon .
assertion "j < idsz" failed: file "ids.c", line 87, function "idents_assign_uid"
Abort trap (core dumped) 
...
(gdb) backtrace
#0  thrkill () at -:3
#1  0x00000ecf667b528e in _libc_abort () at /usr/src/lib/libc/stdlib/abort.c:51
#2  0x00000ecf6676bb92 in _libc___assert2 (file=Variable "file" is not available.
)
    at /usr/src/lib/libc/gen/assert.c:52
#3  0x00000ecc859b0dce in idents_assign_uid (sess=0x7f7ffffce678, 
    fl=0xece9bb3a000, flsz=18, ids=0x0, idsz=0) at ids.c:87
#4  0x00000ecc859ad762 in flist_recv (sess=0x7f7ffffce678, fd=3, 
    flp=0x7f7ffffce5b8, sz=0x7f7ffffce5a8) at flist.c:771
#5  0x00000ecc859b70c6 in rsync_receiver (sess=0x7f7ffffce678, fdin=3, 
    fdout=3, root=0xecf5a682970 ".") at receiver.c:214
#6  0x00000ecc859bb8af in rsync_socket (opts=0x7f7ffffceb80, f=0xecefd5fd0c0)
    at socket.c:417
#7  0x00000ecc859c0e7f in main (argc=2, argv=0x7f7ffffcf048) at main.c:456

Same for the in-obsd not-yet-linked-to-build rsync(1), but I cloned your version to verify if it was the same error.

**Comment by kristapsdz** [comment]
That should do it!  Let me know if it doesn't.
