### ISSUE TITLE
Feature request: --exclude

### ISSUE THREAD

**Issue by eradman** [kristapsdz/openrsync#14]
I often use `--exclude` when using rsync(1) to back up a home directories. Example:

```
rsync \ 
    --exclude "vm/*" \
    --exclude "*.core" \
    --exclude ".gimp-2.8/gimpswap.*" \
    -va $HOME myuser@remote:~/backup
```

In some cases I can emulate this with openrsync(1) by building a list of directories and running rsync on them individually.

**Comment by kristapsdz** [comment]
Sorry buddy, I don't keep track of feature requests.  Exclusions are something I'd also like, but they'll happen if they do.  Meanwhile, if you'll take a look through rsync's exclusion code and give it a try yourself, I'm happy to help!  It shouldn't be that difficult.
