### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by dachev** [kristapsdz/openrsync#15]
I don't use C very much so I could be missing something, but it seems that this will enter an infinite loop for any value of `sz` >= 2^25 because at each iteration we only sample the lower 24 bits of the integer and completely ignore the rest. This means that after the first iteration, `wsz` can only ever be 0 and progress will effectively stall.

https://github.com/kristapsdz/openrsync/blob/8b612161bd6c251485725af08d352ae1a7d82eca/io.c#L148

**Comment by kristapsdz** [comment]
Fantastic find!  I'll put out a fix on the double.

**Comment by kristapsdz** [comment]
So a fix is in the works anyway, but are you able to actually trigger this condition?  The way I see it, there's no point where io_write_buf could be called with that much data unless a file or link name were that large, and no file-system supports that.  Block data is limited to MAX_CHUNK (32 KB).

**Comment by dachev** [comment]
Nope, I was just reading the code.

**Comment by dachev** [comment]
@kristapsdz this is just bad engineering but I have a feeling that even if I explained why you wouldn't listen. Closing an issue without an explanation though is just rude.
