### ISSUE TITLE
alternative to recallocarray?

### ISSUE THREAD

**Issue by drumbsd** [kristapsdz/openrsync#2]
Hi, i'm trying to porting this project to FreeBSD. I have an only a problem with "recallocarray". Seems not present in FreeBSD. Any ideas?

**Comment by kristapsdz** [comment]
Hi!  This is closed, but I thought I'd answer anyway.  For a portable version, I'd use [oconfigure](https://github.com/kristapsdz/oconfigure), which produces a lot of the OpenBSD-specific functions, and just add some #if/#endif around the specific functions like pledge and unveil.  The challenge is to enact capsicum to provide the same safeties of pledge and unveil.  At this point, though, the project is a bit too fast-moving for portability in that regard.  Let it settle!
